### ISSUE TITLE
怎么改多分类呀？谢谢

### ISSUE THREAD

**Issue by code1230** [linhaow/TextClassify#2]
你好，改多分类主要改哪里呀？还有哪吗
BertConfig.from_pretrained(args.model_name_or_path, num_labels=2)

接的那个GRU要改吗？

**Comment by linhaow** [comment]
GRU那边应该不用，在bert_model里面有一个类别数要修改，还有loss计算的部分要修改，combine.py和预处理部这个分也要修改。我暂时就记得这么多QAQ
